# Sample Questions for strings and arrays

Q1: Implement and algorithm to determine if a string has all unique characters. What if you cannot use additional space? (CIC)

In [35]:
# Last modification: 05/04/2017
import timeit
def unique_characters(s, method = "set1"):
    n = len(s)
    if n > 256: #ASCII characters
        return False
    if method == "set1": #
        return len(set(s)) == n
    elif method == "set2":
        result = set()
        for ch in s:
            if ch in result:
                return False
            result.add(ch)
        return True
    elif method == "dic":
        result = {}
        for ch in s:
            if ch in result.keys():
                return False
            else:
                result[ch] = 1
        return True
    elif method == "O1Space":
        for i in range(n):
            for j in range(i+1,n):
                if s[i] == s[j]:
                    return False
        return True
a_string = "abcdefg"
print("Set1:", min(timeit.repeat(lambda: unique_characters(a_string, method = "set1"))))
print("Set2:", min(timeit.repeat(lambda: unique_characters(a_string, method = "set2"))))
print("dic:", min(timeit.repeat(lambda: unique_characters(a_string, method = "dic"))))
print("O1Space:", min(timeit.repeat(lambda: unique_characters(a_string, method = "O1Space"))))

Set1: 0.8843819859903306
Set2: 1.4786775239626877
dic: 1.793653920001816
O1Space: 5.290229269012343


Q2: Implement a function that reverses a string (CIC)

In [33]:
# Last modification: 05/04/2017
# It's not possible to change characters ina string in place
import timeit
def reverse_string(s, method = "StringSlow"):
    n = len(s)
    if method == "StringSlow":
        result = ""
        for i in range(n - 1, -1, -1):
            result += s[i]
        return result
    elif method == "ListFast":
        result = []
        for i in range(n - 1, -1, -1):
            result.append(s[i])
        return "".join(result)
    elif method == "LazyAss":
        return s[::-1]
a_string = "abcde"
print("StringSlow:", min(timeit.repeat(lambda: reverse_string(a_string, method = "StringSlow"))))
print("ListFast:", min(timeit.repeat(lambda: reverse_string(a_string, method = "ListFast"))))
print("LazyAss", min(timeit.repeat(lambda: reverse_string(a_string, method = "LazyAss"))))

StringSlow: 1.1227399740018882
ListFast: 1.5873763110139407
LazyAss 0.39658338302979246


Q3: Given two strings, write a method todecide if one is permutation of the other one (CIC)

In [ ]:
# Last modification: 05/04/2017
import timeit
def if_two_words_are_permutations(s1, s2):
    if len(s1) != len(s2):
        return False
    dic = {}
    for ch in s1:
        if ch in dic.keys()
            dic[ch] += 1
        else:
            dic[ch] = 1
    for ch in s2:
        if not ch in dic.keys():
            return False
        elif dic[ch] == 0:
            return False
        else:
            dic[ch] -= 1
    return True
a1_string = "abcdef"
a2_string = "feabcd"
print("StringSlow:", min(timeit.repeat(lambda: if_two_words_are_permutations(a1_string, a2_string))))      

Q4: Change the white spaces with '%20'.

In [14]:
# Last modification: 05/04/2017
import timeit
def fill_white_space(s, filler = "%20"):
    result = ""
    in_space = False
    for ch in s:
        if ch != " ":
            if in_space == True:
                result += filler
                in_space = False
            result += ch
        else:
            in_space = True
    if s[0] == " ":
        result = result[len(filler):]
    return result
a_string = "   Mr John    Smith   "
fill_white_space("   Mr John    Smith   ")
print("Time taken:", min(timeit.repeat(lambda: fill_white_space(a_string))))  

Time taken: 2.6245151690091006


'Mr%20John%20Smith'

Q5: Implement a method that does basic string compression and returns the compressed string if it is actually smaller

In [22]:
# Last modificartion: 05/04/2017
import timeit
def string_compressor(s):
    if len(s) <= 1:
        return s
    result = ""
    current_char = s[0]
    num = 1
    for i in range(1,len(s) - 1):
        if s[i] == current_char:
            num += 1
        else:
            result += current_char + str(num)
            current_char = s[i]
            num = 1
    result += current_char + str(num)
    if len(result) < len(s):
        return(result)
    else:
        return(s)
string_compressor("aabccccccddeeee")
print("Time taken:", min(timeit.repeat(lambda: string_compressor("aabccccccddeeee"))))  

Time taken: 3.693453829968348


Q6: Given an image representetated by an $N\times N$ matrix,where each pixel in the image is 4 bytes, write a method to rotate the image by 90 degrees in place.

In [17]:
# Last modification: 05/05/2017
# has not been completed yet
import timeit
import numpy as np
import copy # You have to use a deep copy 
def image_rotation(mat):
    n = mat.shape[0]
    for i in range(n // 2):
        temp = copy.copy(mat[i, i : n-1-i]) # top to temp
        mat[i, i : n-1-i] = mat[range(n - 1 - i, i, -1), i] # left to top
        mat[i + 1 : n - i, i] = mat[n - 1 - i, i + 1: n - i]# bottom to left
        mat[n - 1 - i, i + 1 : n - i] = mat[range(n - 2 - i, i - 1, -1), n - 1 - i]# right to bottom
        mat[i : n - 1 - i, n - 1 - i] = temp # old top to right
    return mat
test = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print("Original matrix:\n",test)
print("Rotated matrix:\n", image_rotation(test))

Original matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Rotated matrix:
 [[13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]
 [16 12  8  4]]


Q7: Write an algorithm such that if an element in $M\times N$ matrix is zero, its entire row and column is set to zero

In [22]:
# Last modification: 05/05/2017
import timeit
import numpy as np
def set_rows_columns_zero(mat):
    m, n = mat.shape
    rows = []
    columns = []
    for i in range(m):
        for j in range(n):
            if mat[i, j] == 0:
                rows.append(i)
                columns.append(j)
    mat[rows, :] = 0
    mat[:, columns] = 0
    return mat
test = np.array([[1,2,3,4,0],[6,7,8,9,10],[0,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("Time taken:", min(timeit.repeat(lambda: set_rows_columns_zero(test))))  

Time taken: 24.090871107997373


Q8: Assume you have a method isSubstring which checks whether one words is a substring of another. Given two strings s1 and s2, write code to check whether s2 is a rotation of s1 which just one time use of isSubstring.

In [28]:
# Last modification: 05/05/2017
# This is the fastet method.
import timeit
def is_rotated(s1, s2):
    if len(s1) != len(s2):
        return False
    return s2 in s1 + s1
s1 = "waterbottle"
s2 = "terbottlewa"
is_rotated(s1, s2)
print("Time taken:", min(timeit.repeat(lambda: is_rotated(s1, s2))))  

Time taken: 0.4020665190182626
